apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cm-staging 
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: maurere.z.i.p@gmail.com
    privateKeySecretRef:
      name: cm-staging
    solvers:
    - http01:
        ingress:
          class: nginx